local adapter = require("dbab.core.adapter")

describe("adapter", function()
  describe("parse_url", function()
    describe("postgres", function()
      it("parses full postgres URL", function()
        local result = adapter.parse_url("postgres://user:pass@localhost:5432/mydb")
        assert.are.equal("postgres", result.scheme)
        assert.are.equal("user", result.user)
        assert.are.equal("pass", result.password)
        assert.are.equal("localhost", result.host)
        assert.are.equal("5432", result.port)
        assert.are.equal("mydb", result.database)
      end)

      it("parses postgresql scheme", function()
        local result = adapter.parse_url("postgresql://user@localhost/mydb")
        assert.are.equal("postgresql", result.scheme)
        assert.are.equal("user", result.user)
        assert.are.equal("localhost", result.host)
        assert.are.equal("mydb", result.database)
      end)

      it("parses URL without password", function()
        local result = adapter.parse_url("postgres://user@localhost:5432/mydb")
        assert.are.equal("user", result.user)
        assert.is_nil(result.password)
      end)

      it("parses URL without port", function()
        local result = adapter.parse_url("postgres://user:pass@localhost/mydb")
        assert.are.equal("localhost", result.host)
        assert.is_nil(result.port)
        assert.are.equal("mydb", result.database)
      end)

      it("parses URL without auth", function()
        local result = adapter.parse_url("postgres://localhost/mydb")
        assert.is_nil(result.user)
        assert.is_nil(result.password)
        assert.are.equal("localhost", result.host)
        assert.are.equal("mydb", result.database)
      end)

      it("parses URL with query params", function()
        local result = adapter.parse_url("postgres://localhost/mydb?sslmode=require&timeout=10")
        assert.are.equal("mydb", result.database)
        assert.is_not_nil(result.params)
        assert.are.equal("require", result.params.sslmode)
        assert.are.equal("10", result.params.timeout)
      end)
    end)

    describe("mysql", function()
      it("parses full mysql URL", function()
        local result = adapter.parse_url("mysql://root:secret@127.0.0.1:3306/testdb")
        assert.are.equal("mysql", result.scheme)
        assert.are.equal("root", result.user)
        assert.are.equal("secret", result.password)
        assert.are.equal("127.0.0.1", result.host)
        assert.are.equal("3306", result.port)
        assert.are.equal("testdb", result.database)
      end)

      it("parses mariadb scheme", function()
        local result = adapter.parse_url("mariadb://user:pass@localhost/mydb")
        assert.are.equal("mariadb", result.scheme)
        assert.are.equal("user", result.user)
        assert.are.equal("mydb", result.database)
      end)

      it("parses URL with login-path param", function()
        local result = adapter.parse_url("mysql://localhost/mydb?login-path=local")
        assert.are.equal("local", result.params["login-path"])
      end)
    end)

    describe("sqlite", function()
      it("parses sqlite:/// with absolute path", function()
        local result = adapter.parse_url("sqlite:///tmp/test.db")
        assert.are.equal("sqlite", result.scheme)
        assert.are.equal("/tmp/test.db", result.database)
      end)

      it("parses sqlite:/// with home path", function()
        local result = adapter.parse_url("sqlite:///home/user/data.db")
        assert.are.equal("sqlite", result.scheme)
        assert.are.equal("/home/user/data.db", result.database)
      end)

      it("parses sqlite:// with relative path", function()
        local result = adapter.parse_url("sqlite://my.db")
        assert.are.equal("sqlite", result.scheme)
        assert.are.equal("my.db", result.database)
      end)

      it("parses sqlite:/// with nested path", function()
        local result = adapter.parse_url("sqlite:///var/lib/app/data.db")
        assert.are.equal("sqlite", result.scheme)
        assert.are.equal("/var/lib/app/data.db", result.database)
      end)

      it("returns empty string when no path", function()
        local result = adapter.parse_url("sqlite://")
        assert.are.equal("sqlite", result.scheme)
        assert.are.equal("", result.database)
      end)
    end)

    describe("unknown scheme", function()
      it("parses unknown scheme", function()
        local result = adapter.parse_url("mongodb://localhost/mydb")
        assert.are.equal("mongodb", result.scheme)
        assert.are.equal("localhost", result.host)
        assert.are.equal("mydb", result.database)
      end)
    end)
  end)

  describe("build_cmd", function()
    before_each(function()
      local connection = require("dbab.core.connection")
      connection.active_url = nil
      connection.active_name = nil
    end)

    describe("postgres", function()
      it("returns psql with URL", function()
        local cmd, args = adapter.build_cmd("postgres://localhost/mydb")
        assert.are.equal("psql", cmd)
        assert.are.equal(1, #args)
        assert.are.equal("postgres://localhost/mydb", args[1])
      end)
    end)

    describe("mysql", function()
      it("returns mysql with parsed args", function()
        local cmd, args = adapter.build_cmd("mysql://user:pass@localhost:3306/mydb")
        assert.are.equal("mysql", cmd)

        local arg_str = table.concat(args, " ")
        assert.is_true(arg_str:find("-h") ~= nil)
        assert.is_true(arg_str:find("localhost") ~= nil)
        assert.is_true(arg_str:find("-P") ~= nil)
        assert.is_true(arg_str:find("3306") ~= nil)
        assert.is_true(arg_str:find("-u") ~= nil)
        assert.is_true(arg_str:find("user") ~= nil)
        assert.is_true(arg_str:find("-ppass") ~= nil)
        assert.is_true(arg_str:find("mydb") ~= nil)
      end)

      it("builds mysql with login-path", function()
        local _, args = adapter.build_cmd("mysql://localhost/mydb?login-path=local")
        local arg_str = table.concat(args, " ")
        assert.is_true(arg_str:find("--login%-path=local") ~= nil)
      end)

      it("builds mysql without optional fields", function()
        local cmd, args = adapter.build_cmd("mysql://localhost/mydb")
        assert.are.equal("mysql", cmd)
        local arg_str = table.concat(args, " ")
        assert.is_true(arg_str:find("localhost") ~= nil)
        assert.is_true(arg_str:find("mydb") ~= nil)
        assert.is_nil(arg_str:find("-P"))
        assert.is_nil(arg_str:find("-u"))
      end)
    end)

    describe("sqlite", function()
      it("returns sqlite3 with database path", function()
        local cmd, args = adapter.build_cmd("sqlite:///tmp/test.db")
        assert.are.equal("sqlite3", cmd)
        assert.are.equal(1, #args)
        assert.are.equal("/tmp/test.db", args[1])
      end)
    end)

    it("errors on unsupported database type", function()
      assert.has_error(function()
        adapter.build_cmd("mongodb://localhost/mydb")
      end)
    end)
  end)
end)
